#!/usr/bin/env python3
"""Build ~450-query household corpus for probe:hint-gap --full."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path("/workspace")

# Plan §7 expansions + household variants (RU). Domain tags for reporting.
PLAN: list[tuple[str, str, str | None]] = [
    # food
    ("food", "рис", "grains-pasta"),
    ("food", "мука", "grains-pasta"),
    ("food", "макароны", "grains-pasta"),
    ("food", "гречка", "grains-pasta"),
    ("food", "овсянка", "grains-pasta"),
    ("food", "перловка", "grains-pasta"),
    ("food", "крупа", "grains-pasta"),
    ("food", "лапша", "grains-pasta"),
    ("food", "спагетти", "grains-pasta"),
    ("food", "хлеб", "grains-pasta"),
    ("food", "булка", "grains-pasta"),
    ("food", "печенье", "grains-pasta"),
    ("food", "крекер", "grains-pasta"),
    ("food", "вафли", "grains-pasta"),
    ("food", "торт", "grains-pasta"),
    ("food", "колбаса", "meat"),
    ("food", "сосиски", "meat"),
    ("food", "ветчина", "meat"),
    ("food", "бекон", "meat"),
    ("food", "мясо", "meat"),
    ("food", "говядина", "meat"),
    ("food", "свинина", "meat"),
    ("food", "курица", "meat"),
    ("food", "индейка", "meat"),
    ("food", "рыба", "fish-seafood"),
    ("food", "лосось", "fish-seafood"),
    ("food", "форель", "fish-seafood"),
    ("food", "тунец", "fish-seafood"),
    ("food", "икра", "fish-seafood"),
    ("food", "креветки", "fish-seafood"),
    ("food", "кальмар", "fish-seafood"),
    ("food", "консервы рыбные", "fish-seafood"),
    ("food", "мёд", "pantry-sweet"),
    ("food", "орехи", "pantry-sweet"),
    ("food", "миндаль", "pantry-sweet"),
    ("food", "сахар", "pantry-sweet"),
    ("food", "соль", "pantry-sweet"),
    ("food", "масло подсолнечное", "pantry-sweet"),
    ("food", "масло оливковое", "pantry-sweet"),
    ("food", "уксус", "pantry-sweet"),
    ("food", "кетчуп", "pantry-sweet"),
    ("food", "майонез", "pantry-sweet"),
    ("food", "соус", "pantry-sweet"),
    ("food", "чипсы", "snacks"),
    ("food", "сухарики", "snacks"),
    ("food", "попкорн", "snacks"),
    ("food", "батончик", "snacks"),
    ("food", "жвачка", "snacks"),
    ("food", "мармелад", "snacks"),
    ("food", "сок", "snacks"),
    ("food", "сок апельсиновый", "snacks"),
    ("food", "компот", "snacks"),
    ("food", "морс", "snacks"),
    ("food", "энергетик", "snacks"),
    ("food", "лимонад", "beverages"),
    ("food", "водка", "spirits"),
    ("food", "коньяк", "spirits"),
    ("food", "виски", "spirits"),
    ("food", "ром", "spirits"),
    ("food", "шампанское", "beverages"),
    ("food", "ликёр", "spirits"),
    ("food", "текила", "spirits"),
    ("food", "молоко", "milk"),
    ("food", "йогурт", "milk"),
    ("food", "кефир", "milk"),
    ("food", "сыр", "milk"),
    ("food", "творог", "milk"),
    ("food", "сливочное масло", "milk"),
    ("food", "огурец", "produce-fresh"),
    ("food", "помидор", "produce-fresh"),
    ("food", "картофель", "produce-fresh"),
    ("food", "лук", "produce-fresh"),
    ("food", "морковь", "produce-fresh"),
    ("food", "капуста", "produce-fresh"),
    ("food", "чеснок", "produce-fresh"),
    ("food", "яблоко", "fruit-fresh"),
    ("food", "банан", "fruit-fresh"),
    ("food", "апельсин", "fruit-fresh"),
    ("food", "лимон", "fruit-fresh"),
    ("food", "виноград", "fruit-fresh"),
    ("food", "чай", "tea-coffee"),
    ("food", "кофе", "tea-coffee"),
    ("food", "шоколад", "chocolate"),
    ("food", "суп", "prepared-food"),
    ("food", "суп куриный", "prepared-food"),
    ("food", "борщ", "prepared-food"),
    ("food", "пиво", "beverages"),
    ("food", "вино", "beverages"),
    ("food", "консервы овощные", "produce-fresh"),
    ("food", "рис шлифованный", "grains-pasta"),
    ("food", "мука пшеничная", "grains-pasta"),
    ("food", "хлеб белый", "grains-pasta"),
    ("food", "кола", "beverages"),
    ("food", "минеральная вода", "beverages"),
    ("food", "мороженое", "prepared-food"),
    ("food", "пельмени", "prepared-food"),
    ("food", "пицца", "prepared-food"),
    # apparel
    ("apparel", "носки", None),
    ("apparel", "колготки", None),
    ("apparel", "чулки", None),
    ("apparel", "гольфы", None),
    ("apparel", "майка", "knit-top"),
    ("apparel", "футболка", "knit-top"),
    ("apparel", "худи", "knit-top"),
    ("apparel", "свитер", "knit-top"),
    ("apparel", "рубашка", "woven-apparel"),
    ("apparel", "брюки", "woven-apparel"),
    ("apparel", "джинсы", "woven-apparel"),
    ("apparel", "юбка", "woven-apparel"),
    ("apparel", "куртка", None),
    ("apparel", "пальто", None),
    ("apparel", "пуховик", None),
    ("apparel", "жилет", None),
    ("apparel", "платье", None),
    ("apparel", "сарафан", None),
    ("apparel", "перчатки", None),
    ("apparel", "шарф", None),
    ("apparel", "галстук", None),
    ("apparel", "ремень", None),
    ("apparel", "костюм", None),
    ("apparel", "бельё", None),
    ("apparel", "трусы", None),
    ("apparel", "лифчик", None),
    ("apparel", "кепка", "headgear"),
    ("apparel", "шапка", "headgear"),
    ("apparel", "бейсболка", "headgear"),
    ("apparel", "кроссовки", "footwear"),
    ("apparel", "кеды", "footwear"),
    ("apparel", "ботинки", "footwear"),
    ("apparel", "туфли", "footwear"),
    ("apparel", "сапоги", "footwear"),
    ("apparel", "ткань", "textiles-raw"),
    ("apparel", "хлопок", "textiles-raw"),
    ("apparel", "пряжа", "textiles-raw"),
    ("apparel", "нитки", "textiles-raw"),
    ("apparel", "пижама", None),
    ("apparel", "халат", None),
    ("apparel", "шорты", "woven-apparel"),
    ("apparel", "кардиган", "knit-top"),
    ("apparel", "водолазка", "knit-top"),
    ("apparel", "плащ", None),
    ("apparel", "варежки", None),
    ("apparel", "зонтик", "umbrellas"),
    # home
    ("home", "матрас", "bedroom-furniture"),
    ("home", "кровать", "bedroom-furniture"),
    ("home", "шкаф", "bedroom-furniture"),
    ("home", "комод", "bedroom-furniture"),
    ("home", "полка", "bedroom-furniture"),
    ("home", "зеркало", "bedroom-furniture"),
    ("home", "шторы", "bedroom-furniture"),
    ("home", "жалюзи", "bedroom-furniture"),
    ("home", "кондиционер", "small-appliances"),
    ("home", "обогреватель", "small-appliances"),
    ("home", "вентилятор", "small-appliances"),
    ("home", "чайник", "small-appliances"),
    ("home", "блендер", "small-appliances"),
    ("home", "мультиварка", "small-appliances"),
    ("home", "тостер", "small-appliances"),
    ("home", "кофеварка", "small-appliances"),
    ("home", "кофемашина", "appliances"),
    ("home", "нож", "cutlery"),
    ("home", "вилка", "cutlery"),
    ("home", "ложка", "cutlery"),
    ("home", "термос", "cutlery"),
    ("home", "контейнер", "cutlery"),
    ("home", "стиральный порошок", "cleaning"),
    ("home", "губка", "cleaning"),
    ("home", "швабра", "cleaning"),
    ("home", "средство для мытья", "cleaning"),
    ("home", "диван", "furniture"),
    ("home", "стул", "furniture"),
    ("home", "кресло", "furniture"),
    ("home", "стол", "furniture"),
    ("home", "тарелка", "tableware"),
    ("home", "чашка", "tableware"),
    ("home", "кастрюля", "cookware"),
    ("home", "сковорода", "cookware"),
    ("home", "пылесос", "appliances"),
    ("home", "стиральная машина", "appliances"),
    ("home", "холодильник", "appliances"),
    ("home", "фен", "appliances"),
    ("home", "утюг", "appliances"),
    ("home", "микроволновка", "appliances"),
    ("home", "лампа", "lamps"),
    ("home", "светильник", "lamps"),
    ("home", "люстра", "lamps"),
    ("home", "ковёр", "rugs"),
    ("home", "одеяло", "home-textiles"),
    ("home", "подушка", "home-textiles"),
    ("home", "полотенце", "home-textiles"),
    ("home", "посуда", "tableware"),
    ("home", "миксер", "small-appliances"),
    ("home", "увлажнитель", "small-appliances"),
    ("home", "посудомоечная машина", "appliances"),
    ("home", "чайник электрический", "small-appliances"),
    ("home", "тумбочка", "bedroom-furniture"),
    ("home", "вешалка", None),
    ("home", "корзина для белья", None),
    ("home", "мыло", "personal-care"),
    ("home", "зубная паста", "personal-care"),
    ("home", "шампунь", "cosmetics"),
    ("home", "помада", "cosmetics"),
    # electronics
    ("elec", "ноутбук", "computers"),
    ("elec", "смартфон", None),
    ("elec", "телефон", None),
    ("elec", "планшет", "computers"),
    ("elec", "телевизор", "displays"),
    ("elec", "монитор", "displays"),
    ("elec", "SSD", "pc-parts"),
    ("elec", "HDD", "pc-parts"),
    ("elec", "видеокарта", "pc-parts"),
    ("elec", "процессор", "pc-parts"),
    ("elec", "оперативная память", "pc-parts"),
    ("elec", "блок питания", "pc-parts"),
    ("elec", "материнская плата", "pc-parts"),
    ("elec", "флешка", "pc-parts"),
    ("elec", "карта памяти", "pc-parts"),
    ("elec", "микрофон", "peripherals"),
    ("elec", "модем", "networking"),
    ("elec", "роутер", "networking"),
    ("elec", "свитч", "networking"),
    ("elec", "hdmi кабель", "power"),
    ("elec", "переходник", None),
    ("elec", "кабель", None),
    ("elec", "фотоаппарат", "photo-gear"),
    ("elec", "объектив", "photo-gear"),
    ("elec", "штатив", "photo-gear"),
    ("elec", "GoPro", "photo-gear"),
    ("elec", "наушники", "headphones"),
    ("elec", "колонки", "speakers"),
    ("elec", "саундбар", "speakers"),
    ("elec", "playstation", "gaming"),
    ("elec", "xbox", "gaming"),
    ("elec", "геймпад", "gaming"),
    ("elec", "джойстик", "gaming"),
    ("elec", "камера видеонаблюдения", "security-cam"),
    ("elec", "power bank", "power"),
    ("elec", "зарядка", "power"),
    ("elec", "провод usb", "power"),
    ("elec", "клавиатура", "peripherals"),
    ("elec", "принтер", "printers"),
    ("elec", "сканер", "printers"),
    ("elec", "лампа led", "led"),
    ("elec", "led лента", "led"),
    ("elec", "системный блок", "computers"),
    ("elec", "мышь компьютерная", "peripherals"),
    ("elec", "веб-камера", None),
    ("elec", "наушники bluetooth", "headphones"),
    ("elec", "смарт-часы", "watches"),
    ("elec", "часы", "watches"),
    ("elec", "nintendo", "gaming"),
    ("elec", "steam deck", "gaming"),
    ("elec", "корпус пк", "pc-parts"),
    # auto / chem
    ("auto", "шина", "tires"),
    ("auto", "подшипник", "auto-parts"),
    ("auto", "масляный фильтр", "auto-parts"),
    ("auto", "свечи зажигания", "auto-parts"),
    ("auto", "моторное масло", "auto-fluids"),
    ("auto", "антифриз", "auto-fluids"),
    ("auto", "тормозная жидкость", "auto-fluids"),
    ("auto", "тормозные колодки", "auto-fluids"),
    ("auto", "бампер", "auto-body"),
    ("auto", "фара", "auto-body"),
    ("auto", "дворники", "auto-body"),
    ("auto", "клей", "adhesives-chemicals"),
    ("auto", "смазка", "adhesives-chemicals"),
    ("auto", "WD-40", "adhesives-chemicals"),
    ("auto", "ацетон", "adhesives-chemicals"),
    ("auto", "краска", "paint"),
    ("auto", "обои", "paint"),
    ("auto", "гвозди", "fasteners"),
    ("auto", "шуруп", "fasteners"),
    ("auto", "болт", "fasteners"),
    ("auto", "гайка", "fasteners"),
    ("auto", "аккумулятор", "batteries"),
    ("auto", "батарея", "batteries"),
    ("auto", "шланг", None),
    ("auto", "воздушный фильтр", "auto-parts"),
    ("auto", "маслофильтр", "auto-parts"),
    ("auto", "диск тормозной", "auto-parts"),
    ("auto", "зеркала боковые", "auto-body"),
    ("auto", "колесо", "tires"),
    ("auto", "велосипед", "cycles"),
    ("auto", "самокат", "cycles"),
    # long-tail
    ("long", "ручка", "stationery"),
    ("long", "карандаш", "stationery"),
    ("long", "бумага А4", "stationery"),
    ("long", "скотч", "stationery"),
    ("long", "степлер", "stationery"),
    ("long", "блокнот", "stationery"),
    ("long", "кольцо", "jewelry"),
    ("long", "серьги", "jewelry"),
    ("long", "браслет", "jewelry"),
    ("long", "цепочка", "jewelry"),
    ("long", "гитара", "musical"),
    ("long", "синтезатор", "musical"),
    ("long", "скрипка", "musical"),
    ("long", "барабан", "musical"),
    ("long", "пианино", "musical"),
    ("long", "сигареты", "tobacco"),
    ("long", "табак", "tobacco"),
    ("long", "кальян", "tobacco"),
    ("long", "сигары", "tobacco"),
    ("long", "электронная сигарета", "vape"),
    ("long", "вейп", "vape"),
    ("long", "коляска", "baby-gear"),
    ("long", "пустышка", "baby-gear"),
    ("long", "манеж", "baby-gear"),
    ("long", "автокресло", "baby"),
    ("long", "подгузник", "baby"),
    ("long", "комбикорм", "agri-feed"),
    ("long", "сено", "agri-feed"),
    ("long", "силос", "agri-feed"),
    ("long", "труба", None),
    ("long", "арматура", None),
    ("long", "кабель силовой", "electrical-install"),
    ("long", "розетка", "electrical-install"),
    ("long", "выключатель", "electrical-install"),
    ("long", "термометр", "med-devices"),
    ("long", "тонометр", "med-devices"),
    ("long", "инвалидная коляска", "med-devices"),
    ("long", "ингалятор", "med-devices"),
    ("long", "лыжи", "sports"),
    ("long", "коньки", "sports"),
    ("long", "ролики", "sports"),
    ("long", "ракетка", "sports"),
    ("long", "книга", "books"),
    ("long", "тетрадь", "books"),
    ("long", "учебник", "books"),
    ("long", "журнал", "books"),
    ("long", "картина", "art"),
    ("long", "скульптура", "art"),
    ("long", "сумка", "bags"),
    ("long", "рюкзак", "bags"),
    ("long", "чемодан", "bags"),
    ("long", "игрушка", "toys"),
    ("long", "лего", "toys"),
    ("long", "кукла", "toys"),
    ("long", "конструктор", "toys"),
    ("long", "лекарство", "pharma"),
    ("long", "витамины", "pharma"),
    ("long", "таблетки", "pharma"),
    ("long", "молоток", "tools"),
    ("long", "дрель", "tools"),
    ("long", "шуруповёрт", "tools"),
    ("long", "палатка", "camping"),
    ("long", "спальник", "camping"),
    ("long", "очки", "optics"),
    ("long", "солнечные очки", "optics"),
    ("long", "шприц", "med-disposables"),
    ("long", "бинт", "med-disposables"),
    ("long", "корм для кошек", "pet-food"),
    ("long", "ошейник", "pet-accessories"),
    ("long", "семена", "agri-inputs"),
    ("long", "удобрение", "agri-inputs"),
    ("long", "гербицид", "agri-inputs"),
    ("long", "зонт", "umbrellas"),
    ("long", "мяч", "sports"),
    ("long", "гантели", "sports"),
    ("long", "коврик йога", "sports"),
    ("long", "костыли", "med-devices"),
    ("long", "маска медицинская", "med-disposables"),
    ("long", "фломастер", "stationery"),
    ("long", "ластик", "stationery"),
    ("long", "линейка", "stationery"),
    ("long", "бусы", "jewelry"),
    ("long", "кулон", "jewelry"),
    ("long", "флейта", "musical"),
    ("long", "гармонь", "musical"),
    ("long", "бумага туалетная", None),
    ("long", "подгузники", "baby"),
    ("long", "бутылочка", "baby-gear"),
    ("long", "соска", "baby-gear"),
    ("long", "корм для собак", "pet-food"),
    ("long", "поводок", "pet-accessories"),
    ("long", "миска для животных", "pet-accessories"),
    # policy
    ("policy", "провод", None),
    ("policy", "камера", None),
    ("policy", "фильтр", None),
    ("policy", "свеча", None),
    ("policy", "перец", None),
    ("policy", "кот", None),
    ("policy", "собака", None),
    ("policy", "мышь", None),
    ("policy", "рисовое молоко", None),
    ("policy", "ореховое молоко", None),
    ("policy", "шланг", None),
    ("policy", "переходник", None),
    ("policy", "кабель", None),
]

POLICY = {
    "провод",
    "камера",
    "фильтр",
    "свеча",
    "перец",
    "кот",
    "собака",
    "мышь",
    "рисовое молоко",
    "ореховое молоко",
    "шланг",
    "переходник",
    "кабель",
}


def main() -> None:
    seen: dict[str, dict] = {}

    def add(query: str, domain: str, want: str | None, src: str) -> None:
        q = query.strip()
        if not q:
            return
        key = q.casefold()
        if key in seen:
            return
        seen[key] = {
            "id": f"{domain}.{len(seen):04d}",
            "query": q,
            "domain": domain,
            "source": src,
            "policy": q in POLICY or domain == "policy",
            "wantPack": want,
        }

    for domain, q, want in PLAN:
        add(q, domain, want, "plan-s7")

    prec = json.loads((ROOT / "src/lib/ved/__tests__/hint-pack-precision.fixture.json").read_text())
    for pack in prec["packs"]:
        pid = pack["id"]
        for q in pack.get("positive", []):
            add(q, "precision", pid, "precision-positive")

    d = json.loads((ROOT / "src/lib/ved/__tests__/hint-coverage-probe-dictionary.json").read_text())
    for row in d["rows"]:
        add(row["query"], "golden", row["expected"].get("pack"), "dictionary")

    rows = list(seen.values())
    out = {
        "asOf": "2026-09-01",
        "canon": "docs/knowledge/plan-hint-coverage-expansion.md §7",
        "note": "Full household corpus for observe-mode probe:hint-gap --full. wantPack is a hint, not a hard golden.",
        "rows": rows,
    }
    dest = ROOT / "src/lib/ved/__tests__/hint-coverage-full-corpus.json"
    dest.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n")
    from collections import Counter

    print("rows", len(rows))
    print("by domain", dict(Counter(r["domain"] for r in rows)))
    print("with wantPack", sum(1 for r in rows if r["wantPack"]))
    print("policy", sum(1 for r in rows if r["policy"]))


if __name__ == "__main__":
    main()
